version: "3.3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb

volumes:
  mongodb_data:
